TARGET = asm80
OBJS =	asm1m.o asm2m.o asm3m.o asm4m.o asm5m.o asm6m.o asm8m.o\
		asxref.o cntrlm.o debug.o emitm.o globlm.o initm.o io.o\
		keym.o listm.o pcktok.o rdsrc.o startm.o 

include ../common.mk

$(OBJS): asm80.h data.h error.h literals.h plm80types.h procs.h

