// Autogenerated default version file
#ifndef v0_2_10_3
#define v0_2_10_3
#define GIT_APPID       "plm82"
#define GIT_PORT        "4.0 (C)1975 Intel"
#define GIT_APPNAME     "plm82"
#define GIT_VERSION     "0.2.10x"
#define GIT_VERSION_RC  0,0,0,0
#define GIT_SHA1        "untracked"
#define GIT_BUILDTYPE   2 
#define GIT_CTIME       "2021-08-25 14:10:27"
#define GIT_YEAR        "2021"
#endif
