TARGET = plm80c
OBJS =	accessors.o adninf.o alloc.o allocs.o backup.o cpytil.o creati.o data.o\
	debug.o endcom.o fatal.o fatlio.o fi.o findmi.o fiscop.o io.o itoa.o lookup.o\
	lstinf.o lstlin.o lstsup.o main0.o main1.o main2.o main3.o main4.o main5.o\
	main6.o main.o page.o pdata4.o pdata6.o plm0a.o plm0b.o plm0e.o plm0f.o plm0g.o\
	plm1a.o plm1b.o plm1c.o plm1d.o plm1e.o plm1f.o plm2a.o plm2b.o plm2c.o plm2d.o\
	plm2e.o plm2f.o plm2g.o plm2h.o plm3a.o plm3b.o plm4a.o plm4b.o plm4c.o plm6a.o\
	plma.o plmb.o plmfile.o prints.o putlst.o strcmp.o util.o wrclst.o

include ../common.mk

$(OBJS) : plm.h error.h
