// Autogenerated default version file
#ifndef v0_2_9_3
#define v0_2_9_3
#define GIT_APPID       "lib"
#define GIT_PORT        "2.1 (C)1977 Intel"
#define GIT_APPNAME     "lib"
#define GIT_VERSION     "0.2.9x"
#define GIT_VERSION_RC  0,0,0,0
#define GIT_SHA1        "untracked"
#define GIT_BUILDTYPE   2 
#define GIT_CTIME       "2021-08-25 14:10:25"
#define GIT_YEAR        "2021"
#endif
