// Autogenerated default version file
#ifndef v0_1_5_3
#define v0_1_5_3
#define GIT_APPID       "ml80"
#define GIT_PORT        "(C)1975 Luiz Pedroso"
#define GIT_APPNAME     "ml80"
#define GIT_VERSION     "0.1.5x"
#define GIT_VERSION_RC  0,0,0,0
#define GIT_SHA1        "untracked"
#define GIT_BUILDTYPE   2 
#define GIT_CTIME       "2021-08-25 14:10:25"
#define GIT_YEAR        "2021"
#endif
